### ISSUE TITLE
Yaml documents don't quote strings properly

### ISSUE THREAD

**Issue by SamMousa** [beanstalkd/beanstalkd#610]
The yaml dictionary responses to the stats command seem to not escape tube names and other string values properly.

Since tube names support a lot of styles they are easy to misinterpret by a yaml parser; the following are valid tube names:
- "1.5"
- "12145"

When using these kinds of names the stats result looks like this:
```yaml
---
id: 2590
tube: 0.5
state: ready
pri: 1024
age: 0
delay: 0
ttr: 60
time-left: 0
file: 0
reserves: 0
timeouts: 0
releases: 0
buries: 0
kicks: 0
```

When looking at the output of the `stats` command (showing only a subset):
```yaml
---
current-jobs-urgent: 0
cmd-pause-tube: 32
pid: 1
version: "1.12"
rusage-utime: 0.061179
rusage-stime: 0.327746
uptime: 3371
binlog-max-size: 10485760
draining: false
id: 5b994f05f0b1640a
hostname: 87a060754e5d
os: #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021
platform: x86_64
```

We see some strings (specifically `version`) are properly quoted.
While writing this bug report I found that the OS string being unescaped and containing a `#` causes it to be interpreted as a comment. (For example by this converter: https://jsonformatter.org/yaml-to-json)

A simple solution would be to just quote all string-typed values. This will add some bytes to the output, but could significantly simplify code.
The string keys I found are:
- hostname
- id
- os
- platform
- name (from `stats-tube`)
- tube (from `stats-job`)

From these `os` is unsafe at least on ubuntu, because it starts with `#`, the tube name is unsafe because tube names may look like any other value type (`bool|float|int`) and the hostname may be just numbers.
