### ISSUE TITLE
Invalid yaml response in stats

### ISSUE THREAD

**Issue by silviucpp** [beanstalkd/beanstalkd#640]
```yaml
---
current-jobs-urgent: 3
current-jobs-ready: 3
current-jobs-reserved: 0
current-jobs-delayed: 0
current-jobs-buried: 0
cmd-put: 11
cmd-peek: 1
cmd-peek-ready: 1
cmd-peek-delayed: 1
cmd-peek-buried: 1
cmd-reserve: 5
cmd-reserve-with-timeout: 0
cmd-delete: 8
cmd-release: 1
cmd-use: 9
cmd-watch: 7
cmd-ignore: 7
cmd-bury: 3
cmd-kick: 1
cmd-touch: 1
cmd-stats: 5
cmd-stats-job: 1
cmd-stats-tube: 0
cmd-list-tubes: 0
cmd-list-tube-used: 0
cmd-list-tubes-watched: 0
cmd-pause-tube: 0
job-timeouts: 0
total-jobs: 11
max-job-size: 65535
current-tubes: 3
current-connections: 51
current-producers: 0
current-workers: 0
current-waiting: 0
total-connections: 212
pid: 51280
version: "1.12"
rusage-utime: 0.004663
rusage-stime: 0.010021
uptime: 794
binlog-oldest-index: 0
binlog-current-index: 0
binlog-records-migrated: 0
binlog-records-written: 0
binlog-max-size: 10485760
draining: false
id: a222ea4da2cb7c1a
hostname: 192-168-0-105.rdsnet.ro
os: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64
platform: x86_64
```

Any YAML parser is throwing an error because of the `os`:

```
ERROR:

mapping values are not allowed here
  in "<unicode string>", line 51, column 33:
    os: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022;  ... 
```
